### ISSUE TITLE
Flawed Encryption Logic

### ISSUE THREAD

**Issue by AbhishekTripathi** [VerizonDigital/ectoken#12]
The encryption logic is not idempotent. We found that even if the encrypted value is manipulated, we get the same decrypted value from the SDK and also on the Azure CDN Profile Management portal. I used your class https://github.com/VerizonDigital/ectoken/blob/master/c%23-ectoken/ecencryptstdlib/ECTokenGenerator.cs  to do some analysis and found following -

**Key**
si9sK_jvSALTrlXIVMI4CgIGuu1MJeHXH0B3HxuRP48N5ZYwSa

**Phrase**
&ec_expire=1000000000

**Encrypted Value**
MvBF32ldv2tDtT1QpggWPqENfoxZYmz_ijChwt6O1xenQfoTenOiTuzvVuiUJT2J2Q

**Mutation of Encrypted Values giving same phrase back on decryption**
MvBF32ldv2tDtT1QpggWPqENfoxZYmz_ijChwt6O1xenQfoTenOiTuzvVuiUJT2J2R
MvBF32ldv2tDtT1QpggWPqENfoxZYmz_ijChwt6O1xenQfoTenOiTuzvVuiUJT2J2S
MvBF32ldv2tDtT1QpggWPqENfoxZYmz_ijChwt6O1xenQfoTenOiTuzvVuiUJT2J2T
MvBF32ldv2tDtT1QpggWPqENfoxZYmz_ijChwt6O1xenQfoTenOiTuzvVuiUJT2J2U
MvBF32ldv2tDtT1QpggWPqENfoxZYmz_ijChwt6O1xenQfoTenOiTuzvVuiUJT2J2V
MvBF32ldv2tDtT1QpggWPqENfoxZYmz_ijChwt6O1xenQfoTenOiTuzvVuiUJT2J2W
MvBF32ldv2tDtT1QpggWPqENfoxZYmz_ijChwt6O1xenQfoTenOiTuzvVuiUJT2J2X
MvBF32ldv2tDtT1QpggWPqENfoxZYmz_ijChwt6O1xenQfoTenOiTuzvVuiUJT2J2Y
MvBF32ldv2tDtT1QpggWPqENfoxZYmz_ijChwt6O1xenQfoTenOiTuzvVuiUJT2J2Z

**Comment by hattan** [comment]
Thanks, @AbhishekTripathi . We'll investigate this issue and provide an update shortly.
