### ISSUE TITLE
NodeJS support

### ISSUE THREAD

**Issue by adamthesax** [VerizonDigital/ectoken#17]
We are planning on integrating EdgeCast into our backend system which is written in NodeJS. Would you be open to a Pull Request with a NodeJS implementation of ectoken?

**Comment by hattan** [comment]
Hi @monkpod. Sorry for the delay.

We have a nodejs version in the pipeline. We should be releasing it shortly (hopefully within the next 2 weeks)

**Comment by monkpod** [comment]
Great! Thanks for following up, looking forward to leveraging the nodejs implementation.

**Comment by tomalex0** [comment]
@hattan i came across  a repo
https://github.com/rfrench/ectoken-nodejs
Is this a valid one ?

Also https://github.com/VerizonDigital/ectoken-nodejs  which is empty.

**Comment by tomalex0** [comment]
thanks @airencracken  for the update 👍
