### ISSUE TITLE
PHP implementation requires a PHP extension

### ISSUE THREAD

**Issue by Monstrel** [VerizonDigital/ectoken#21]
Implementation of ectoken in PHP applications is hindered in environments that don't allow the installation of custom PHP extensions.

I am developing a native PHP implementation that will have similar platform requirements as the existing php-ectoken implementation (PHP 5.4+ or PHP 7.x+, with or without openssl or mbstring modules) but which will not require a PHP extension.

A PR will be forthcoming. (from my other Github account. Whoops!)

**Comment by airencracken** [comment]
Merged your fork's code into https://github.com/VerizonDigital/php-ectoken/
