### ISSUE TITLE
License Inconsistencies...

### ISSUE THREAD

**Issue by apollak** [VerizonDigital/ectoken#3]
In the root folder there is a Apache License defined, but in the source code of the token generation we found this part in the source files:

"Use of source and binary forms, with or without modification is permitted provided that there is written consent by EdgeCast Networks, Inc. Redistribution in source and binary forms  is not permitted."

This basically requires every Azure CDN customer who wants to use the token authentication to get a written consent by EdgeCast Networks. Also the second part forces each customer to adapt the code to use it in production instead of making use of an open source contribution to ease the process f.e. by using an extended library provided as nugget package from open source contributors.

Could you please clarify on that?

Thnx
 Andreas

**Comment by tinselcity** [comment]
The external Apache License is "the" license.  I'll work on updating the source to reflect this.

**Comment by tinselcity** [comment]
commited: c0b67f7 -hopefully this resolves issue.
