### ISSUE TITLE
Does not work with .net core.

### ISSUE THREAD

**Issue by johnkwaters** [VerizonDigital/ectoken#4]
Depends on BouncyCastle.Crypto which does not exist in dotnet core.

**Comment by apollak** [comment]
I planned to fix that by implementing a open source library, but until the licencing issue is not taken care of, I am not touching this.

**Comment by tinselcity** [comment]
@apollak I'm no .NET wonk, I'd love to take your changes.  Let me know if the licensing issues have been redressed.

**Comment by apollak** [comment]
@tinselcity  I will shared them with you as soon as I can take the time to implement it :-) Thnx for fixing the licensing issues!

**Comment by apollak** [comment]
@johnkwaters , @tinselcity - I implemented a .NET Standard 1.4 compliant version at https://github.com/apollak/ectoken/tree/master/c%23-ectoken  (needs testing, still in an early development stage). You might want to have a look at it.

**Comment by tinselcity** [comment]
Thanks I've merged it in.  Hopefully resolved this issue.

**Comment by apollak** [comment]
:-) I have started a small library to ease the process using it with ASP.NET Core. Happy for suggestions: https://github.com/SpectoLogic/SpectoLogic.Azure.CDN/blob/master/SpectoLogic.Azure.CDN/readme.md
