### ISSUE TITLE
Slightly off results in .net core

### ISSUE THREAD

**Issue by johnkwaters** [VerizonDigital/ectoken#6]
The .net core version works nicely, execept it doenst generate EXACTLY the same tokens as the online tool does when using Azure CDN. I wonder of it might be to do with the order of the parameters that get encoded?

**Comment by apollak** [comment]
The tokens need to look different every time you create them as the Initialization Vector is created randomly everytime. 

            byte[] iv = new byte[NonceBitSize / 8];
            Random.NextBytes(iv, 0, iv.Length);
            var cipher = new GcmBlockCipher(new AesFastEngine());
            // var parameters = new AeadParameters(new KeyParameter(key), MacBitSize, nonce, nonSecretPayload);
            KeyParameter keyParam = new KeyParameter(key);
            ICipherParameters parameters = new ParametersWithIV(keyParam, iv);
            cipher.Init(true, parameters);
